export const phonesConstants = {
  GET_ALL_REQUEST: "PHONES_GET_ALL_REQUEST",
  GET_ALL_SUCCESS: "PHONES_GET_ALL_SUCCESS",
  GET_ALL_ERROR: "PHONES_GET_ALL_ERROR",

  GET_ONE_REQUEST: "PHONES_GET_ONE_REQUEST",
  GET_ONE_SUCCESS: "PHONES_GET_ONE_SUCCESS",
  GET_ONE_ERROR: "PHONES_GET_ONE_ERROR",

  ADD_SUCCESS: "PHONES_ADD_SUCCESS",
  ADD_ERROR: "PHONES_ADD_ERROR",

  UPDATE_SUCCESS: "PHONES_UPDATE_SUCCESS",
  UPDATE_ERROR: "PHONES_UPDATE_ERROR",

  DELETE_SUCCESS: "PHONES_DELETE_SUCCESS",
  DELETE_ERROR: "PHONES_DELETE_ERROR"
};
